# -*- coding: utf-8 -*-
"""trained_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHWvUNlWoJtsfNHpfh5EpgVRWr0Rx497
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pickle

# --- Load training data ---
train_df = pd.read_excel("Titanic_train.csv.xlsx")

# --- Preprocess training data ---
train_df = train_df.dropna(subset=["Age", "Fare", "Embarked", "Sex"])
train_df["Sex"] = train_df["Sex"].map({"male": 0, "female": 1})
train_df["Embarked"] = train_df["Embarked"].map({"S": 0, "C": 1, "Q": 2})

features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
X = train_df[features]
y = train_df["Survived"]

# --- Train model ---
model = LogisticRegression(max_iter=1000)
model.fit(X, y)

# --- Save model and columns ---
with open("model.pkl", "wb") as f:
    pickle.dump({
        "model": model,
        "columns": X.columns.tolist()
    }, f)

print("✅ Model trained and saved as model.pkl")

# --- Load test data ---
test_df = pd.read_excel("Titanic_test.csv.xlsx")

# --- Preprocess test data ---
test_df = test_df.dropna(subset=["Age", "Fare", "Embarked", "Sex"])
test_df["Sex"] = test_df["Sex"].map({"male": 0, "female": 1})
test_df["Embarked"] = test_df["Embarked"].map({"S": 0, "C": 1, "Q": 2})

# --- Load model ---
with open("model.pkl", "rb") as f:
    model_data = pickle.load(f)
    model = model_data["model"]
    expected_cols = model_data["columns"]

# --- Align test data ---
X_test = test_df[expected_cols]

# --- Predict ---
predictions = model.predict(X_test)
probabilities = model.predict_proba(X_test)[:, 1]

# --- Add predictions to test data ---
test_df["Survived_Prediction"] = predictions
test_df["Survival_Probability"] = probabilities

# --- Show results ---
print(test_df[["Name", "Survived_Prediction", "Survival_Probability"]].head())

